//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSVImportParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSVImportParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все файлы|*.*|.
        /// </summary>
        internal static string ВсеФайлы {
            get {
                return ResourceManager.GetString("ВсеФайлы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите название для шаблона импорта.
        /// </summary>
        internal static string ВыберитеНазваниеДляШаблонаИмпорта {
            get {
                return ResourceManager.GetString("ВыберитеНазваниеДляШаблонаИмпорта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите шаблон импорта.
        /// </summary>
        internal static string ВыберитеШаблонИмпорта {
            get {
                return ResourceManager.GetString("ВыберитеШаблонИмпорта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный шаблон импорта не подходит к загруженным данным.
        /// </summary>
        internal static string ВыбранныйШаблонИмпортаНеПодходитКЗагруженн {
            get {
                return ResourceManager.GetString("ВыбранныйШаблонИмпортаНеПодходитКЗагруженн", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        internal static string Готово {
            get {
                return ResourceManager.GetString("Готово", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка данных.
        /// </summary>
        internal static string ЗагрузкаДанных {
            get {
                return ResourceManager.GetString("ЗагрузкаДанных", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игнор..
        /// </summary>
        internal static string Игнор {
            get {
                return ResourceManager.GetString("Игнор", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не все обязательные для импорта поля задействованны.
        ///Используйте контекстное меню на заголовках столбцов таблицы для выбора назначения полей..
        /// </summary>
        internal static string НеВсеОбязательныеДляИмпортаПоляЗадействова {
            get {
                return ResourceManager.GetString("НеВсеОбязательныеДляИмпортаПоляЗадействова", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Не использ.&gt;.
        /// </summary>
        internal static string НеИспольз {
            get {
                return ResourceManager.GetString("НеИспольз", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо устранить все ошибки в данных перед импортированием..
        /// </summary>
        internal static string НеобходимоУстранитьВсеОшибкиВДанныхПередИм {
            get {
                return ResourceManager.GetString("НеобходимоУстранитьВсеОшибкиВДанныхПередИм", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработка....
        /// </summary>
        internal static string Обработка {
            get {
                return ResourceManager.GetString("Обработка", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string Ошибка {
            get {
                return ResourceManager.GetString("Ошибка", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка загрузки шаблона.
        /// </summary>
        internal static string ОшибкаЗагрузкиШаблона {
            get {
                return ResourceManager.GetString("ОшибкаЗагрузкиШаблона", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка импорта.
        /// </summary>
        internal static string ОшибкаИмпорта {
            get {
                return ResourceManager.GetString("ОшибкаИмпорта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка экспорта таблицы.
        /// </summary>
        internal static string ОшибкаЭкспортаТаблицы {
            get {
                return ResourceManager.GetString("ОшибкаЭкспортаТаблицы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибки в импортируемых данных.
        /// </summary>
        internal static string ОшибкиВИмпортируемыхДанных {
            get {
                return ResourceManager.GetString("ОшибкиВИмпортируемыхДанных", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string ТекстЗаголовкаОкнаИмпорта {
            get {
                return ResourceManager.GetString("ТекстЗаголовкаОкнаИмпорта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы шаблонов импорта (*.tpl)|*.tpl.
        /// </summary>
        internal static string ФайлыШаблоновИмпортаImportxImportx {
            get {
                return ResourceManager.GetString("ФайлыШаблоновИмпортаImportxImportx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы CSV|*.csv.
        /// </summary>
        internal static string ФильтрФайловCSV {
            get {
                return ResourceManager.GetString("ФильтрФайловCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблон.
        /// </summary>
        internal static string Шаблон {
            get {
                return ResourceManager.GetString("Шаблон", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт данных из таблицы.
        /// </summary>
        internal static string ЭкспортДанныхИзТаблицы {
            get {
                return ResourceManager.GetString("ЭкспортДанныхИзТаблицы", resourceCulture);
            }
        }
    }
}
